all: default/cgi-bin/hello.cgi default/cgi-bin/post.cgi
	@echo "done"

default/cgi-bin/hello.cgi:
	@c++ default/cgi-bin/hello.cpp -o default/cgi-bin/hello.cgi

default/cgi-bin/post.cgi:
	@c++ default/cgi-bin/post.cpp -o default/cgi-bin/post.cgi